### ISSUE TITLE
What is the purpose of `externals` in the generated manifest? 

### ISSUE THREAD

**Issue by SaurabhKshirsagar** [cerebral/webpack-packager#25]
While using webpack.DllPlugin the outcome is manifest.json is like.
> {
>   name:"vendor_lib"
>   content:{
>     "./node_modules/fbjs/lib/invariant.js": 0,
>     "./node_modules/fbjs/lib/warning.js": 1,
>      . . .
>    }
> }

But while i am requesting webpack-packager service the manifest is like.
> {
>   name:"dll_bundle"
>   content:{
>     "./node_modules/fbjs/lib/invariant.js": 0,
>     "./node_modules/fbjs/lib/warning.js": 1,
>      . . .
>    }
>    externals:{
>        "fbjs/lib/invariant.js": "dll_bundle(0)",
>        "fbjs/lib/invariant": "dll_bundle(0)"
>    }
> }

**Basically, `externals` are added in addition to `name` and `content`. This definitely should help somewhere in mapping import/require to the right dll_bundle call. Is this correct?**

**Comment by CompuIves** [comment]
You're right, they are specifically used by CodeSandbox to map require statements to the correct module id.
